# Generated by Django 3.0.8 on 2020-07-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.TextField(default='No comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='N/A', max_length=80),
        ),
    ]
