# Generated by Django 3.0.8 on 2020-07-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200718_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.TextField(blank=True, default='No comment', null=True),
        ),
    ]
